/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Tuesday, August 20, 2019
 ***********************************************************************************************/

#ifndef DIGITALTWIN_SERIALIZER
#define DIGITALTWIN_SERIALIZER

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include "azure_c_shared_utility/xlogging.h"
#include "parson.h"

#include "../esp32AzureKit_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

bool Sensor_SerializeTempTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeHumidTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeLightTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializePitchTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeRollTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializePressureTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeAltitudeTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeMagnetXTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeMagnetYTelemetry(char * payloadBuffer, int size);

bool Sensor_SerializeMagnetZTelemetry(char * payloadBuffer, int size);

bool Deviceinfo_SerializeManufacturerProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeModelProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeSwVersionProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeOsNameProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeTotalStorageProperty(char * payloadBuffer, int size);

bool Deviceinfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size);

bool Sensor_SerializeEchoCommandResponse(char* response, char* payloadBuffer, int size);

#ifdef __cplusplus
}
#endif

#endif // DIGITALTWIN_SERIALIZER
