#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := prov_dev_client_ll_sample_symm_keys

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../esp-azure

include $(IDF_PATH)/make/project.mk
