/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Tuesday, August 20, 2019
 ***********************************************************************************************/

#include "digitaltwin_serializer.h"

//
// Serialize telemetry data
//

bool Sensor_SerializeTempTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double temp = Sensor_Telemetry_ReadTemp();

    int neededSize = snprintf(NULL, 0, "%f", temp);

    if (neededSize > size - 1)
    {
        LogError("Failed to build temp payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", temp);
    }

    return true;
}

bool Sensor_SerializeHumidTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double humid = Sensor_Telemetry_ReadHumid();

    int neededSize = snprintf(NULL, 0, "%f", humid);

    if (neededSize > size - 1)
    {
        LogError("Failed to build humid payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", humid);
    }

    return true;
}

bool Sensor_SerializeLightTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double light = Sensor_Telemetry_ReadLight();

    int neededSize = snprintf(NULL, 0, "%f", light);

    if (neededSize > size - 1)
    {
        LogError("Failed to build light payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", light);
    }

    return true;
}

bool Sensor_SerializePitchTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long pitch = Sensor_Telemetry_ReadPitch();

    int neededSize = snprintf(NULL, 0, "%ld", pitch);

    if (neededSize > size - 1)
    {
        LogError("Failed to build pitch payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", pitch);
    }

    return true;
}

bool Sensor_SerializeRollTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long roll = Sensor_Telemetry_ReadRoll();

    int neededSize = snprintf(NULL, 0, "%ld", roll);

    if (neededSize > size - 1)
    {
        LogError("Failed to build roll payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", roll);
    }

    return true;
}

bool Sensor_SerializePressureTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double pressure = Sensor_Telemetry_ReadPressure();

    int neededSize = snprintf(NULL, 0, "%f", pressure);

    if (neededSize > size - 1)
    {
        LogError("Failed to build pressure payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", pressure);
    }

    return true;
}

bool Sensor_SerializeAltitudeTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double altitude = Sensor_Telemetry_ReadAltitude();

    int neededSize = snprintf(NULL, 0, "%f", altitude);

    if (neededSize > size - 1)
    {
        LogError("Failed to build altitude payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", altitude);
    }

    return true;
}

bool Sensor_SerializeMagnetXTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetX = Sensor_Telemetry_ReadMagnetX();

    int neededSize = snprintf(NULL, 0, "%ld", magnetX);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetX payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetX);
    }

    return true;
}

bool Sensor_SerializeMagnetYTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetY = Sensor_Telemetry_ReadMagnetY();

    int neededSize = snprintf(NULL, 0, "%ld", magnetY);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetY payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetY);
    }

    return true;
}

bool Sensor_SerializeMagnetZTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long magnetZ = Sensor_Telemetry_ReadMagnetZ();

    int neededSize = snprintf(NULL, 0, "%ld", magnetZ);

    if (neededSize > size - 1)
    {
        LogError("Failed to build MagnetZ payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", magnetZ);
    }

    return true;
}

//
// Serialize read-only property
//

bool Deviceinfo_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = Deviceinfo_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool Deviceinfo_SerializeModelProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* model = Deviceinfo_Property_GetModel();

    int neededSize = snprintf(NULL, 0, "\"%s\"", model);

    if (neededSize > size - 1)
    {
        LogError("Failed to build model payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", model);
    }

    return true;
}

bool Deviceinfo_SerializeSwVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* swVersion = Deviceinfo_Property_GetSwVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", swVersion);

    if (neededSize > size - 1)
    {
        LogError("Failed to build swVersion payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", swVersion);
    }

    return true;
}

bool Deviceinfo_SerializeOsNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* osName = Deviceinfo_Property_GetOsName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", osName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build osName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", osName);
    }

    return true;
}

bool Deviceinfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorArchitecture = Deviceinfo_Property_GetProcessorArchitecture();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorArchitecture);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorArchitecture payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorArchitecture);
    }

    return true;
}

bool Deviceinfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorManufacturer = Deviceinfo_Property_GetProcessorManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorManufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorManufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorManufacturer);
    }

    return true;
}

bool Deviceinfo_SerializeTotalStorageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    int totalStorage = Deviceinfo_Property_GetTotalStorage();

    int neededSize = snprintf(NULL, 0, "%d", totalStorage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalStorage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", totalStorage);
    }

    return true;
}

bool Deviceinfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    int totalMemory = Deviceinfo_Property_GetTotalMemory();

    int neededSize = snprintf(NULL, 0, "%d", totalMemory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalMemory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", totalMemory);
    }

    return true;
}

bool Sensor_SerializeEchoCommandResponse(char* response, char* payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    int neededSize = snprintf(NULL, 0, "\"%s\"", response);

    if (neededSize > size - 1)
    {
        LogError("Failed to build echo response payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", response);
    }

    return true;
}