#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := iothub_devicetwin_samples_and_methods

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../esp-azure

include $(IDF_PATH)/make/project.mk
