/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Tuesday, August 20, 2019
 ***********************************************************************************************/

#ifndef ESP32AZUREKIT_IMPL
#define ESP32AZUREKIT_IMPL

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"
#include "parson.h"

/**
* @brief Result of DigitalTwin command execution.
*/
typedef enum DIGITALTWIN_COMMAND_RESULT_TAG
{
    DIGITALTWIN_COMMAND_OK,
    DIGITALTWIN_COMMAND_TIMEOUT,
    DIGITALTWIN_COMMAND_ERROR
} DIGITALTWIN_COMMAND_RESULT;

// Device telemetries related APIs

double Sensor_Telemetry_ReadTemp();

double Sensor_Telemetry_ReadHumid();

double Sensor_Telemetry_ReadLight();

long Sensor_Telemetry_ReadPitch();

long Sensor_Telemetry_ReadRoll();

double Sensor_Telemetry_ReadPressure();

double Sensor_Telemetry_ReadAltitude();

long Sensor_Telemetry_ReadMagnetX();

long Sensor_Telemetry_ReadMagnetY();

long Sensor_Telemetry_ReadMagnetZ();

// Callbacks to handle the confirmation result of sending telemetry
void SendTelemetry_Succeeded_Callback(const char* interfaceName, const char* telemetryName);
void SendTelemetry_Error_Callback(const char* interfaceName, const char* telemetryName);

// Callbacks to handle the confirmation result of reporting property
void ReportProperty_Succeeded_Callback(const char* interfaceName, const char* telemetryName);
void ReportProperty_Error_Callback(const char* interfaceName, const char* telemetryName);

// Device properties related APIs

char* Deviceinfo_Property_GetManufacturer();

char* Deviceinfo_Property_GetModel();

char* Deviceinfo_Property_GetSwVersion();

char* Deviceinfo_Property_GetOsName();

char* Deviceinfo_Property_GetProcessorArchitecture();

char* Deviceinfo_Property_GetProcessorManufacturer();

int Deviceinfo_Property_GetTotalStorage();

int Deviceinfo_Property_GetTotalMemory();



bool Sensor_Property_FanSpeedCallback(double fanSpeed);

bool Sensor_Property_TempThresholdCallback(double tempThreshold);

// Device commands related APIs

DIGITALTWIN_COMMAND_RESULT Sensor_Command_Echo(char* displayedValue, char** response, unsigned int* statusCode);

DIGITALTWIN_COMMAND_RESULT Sensor_Command_StartFan(unsigned int* statusCode);

DIGITALTWIN_COMMAND_RESULT Sensor_Command_StopFan(unsigned int* statusCode);

#ifdef __cplusplus
}
#endif

#endif // ESP32AZUREKIT_IMPL
